"""add vto table

Revision ID: 049f40a40ae3
Revises: 4b80bc649015
Create Date: 2026-08-17 13:30:21.486067

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '049f40a40ae3'
down_revision: Union[str, Sequence[str], None] = '4b80bc649015'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vtos',
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('core_values', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('core_focus_purpose', sa.Text(), nullable=True),
    sa.Column('core_focus_niche', sa.Text(), nullable=True),
    sa.Column('ten_year_target', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('three_year_picture', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('one_year_plan', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vtos')
    # ### end Alembic commands ###
