"""make todo issue_id nullable

Revision ID: 628615f6a962
Revises: 656a639e9a2c
Create Date: 2026-08-17 14:12:51.358379

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '628615f6a962'
down_revision: Union[str, Sequence[str], None] = '656a639e9a2c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('todos', 'issue_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('todos', 'issue_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
