"""add people analyzer entries table

Revision ID: 656a639e9a2c
Revises: 049f40a40ae3
Create Date: 2026-08-17 13:32:33.543617

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '656a639e9a2c'
down_revision: Union[str, Sequence[str], None] = '049f40a40ae3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('people_analyzer_entries',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('seat_id', sa.UUID(), nullable=False),
    sa.Column('evaluated_at', sa.Date(), nullable=False),
    sa.Column('gets_it', sa.Boolean(), nullable=False),
    sa.Column('wants_it', sa.Boolean(), nullable=False),
    sa.Column('has_capacity', sa.Boolean(), nullable=False),
    sa.Column('core_values_ratings', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['seat_id'], ['seats.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('people_analyzer_entries')
    # ### end Alembic commands ###
